### PR TITLE
added support for multiple audiences

### PR DESCRIPTION
**Pull request by sunsided**
same as #4 but for `dev` branch

### CODE REVIEW

**Comment by PinpointTownes** [comment]
No unit testing love for the dev branch? :smile:

**Comment by sunsided** [comment]
meh :neutral_face:

**Comment by PinpointTownes** [comment]
Merged, thanks @sunsided! :gift: 

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/commit/34a3b0959724cd20fa9997c899a6ebc239369e8a

**Comment by sunsided** [comment]
whoop whoop!

**Pull request closed without merging**
